### ISSUE TITLE
Addon crashing after a while

### ISSUE THREAD

**Issue by Anttibay** [jshank/bwalink#18]
Hello, I am fairly new HA user and thus not so familiar yet with all the technical details with custom components. Hopefully I could get some help here!

I was able to complete the hot tub BWALink installation successfully and got the HA addon working as well and the controls and sensors through MQQT discovery. However, after the addon has been running for a while (like 30 mins or so) and then I toggle e.g. lights on, it crashes. After startup it works nicely for some time and the controls work, it gets the sensor status etc correctly. Addon logs are also clear until I try to toggle something, then I get the following (bolded entries):

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[13:06:03] INFO: Starting BWALink addon...
[13:06:03] INFO: Setting addon timezone to Europe/Helsinki based on the system timezone.
[13:06:04] INFO: Starting mqtt bridge connecting tcp://192.168.100.63:8899/ to mqtt://core-mosquitto:1883
W, Balboa MQTT Bridge running (version 2.1.5)
**/usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/lib/bwa/client.rb:74:in `readpartial': Connection reset by peer (Errno::ECONNRESET)
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/lib/bwa/client.rb:74:in `block in poll'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/lib/bwa/client.rb:64:in `loop'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/lib/bwa/client.rb:64:in `poll'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/exe/bwa_mqtt_bridge:59:in `block in initialize'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/exe/bwa_mqtt_bridge:58:in `loop'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/exe/bwa_mqtt_bridge:58:in `initialize'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/exe/bwa_mqtt_bridge:421:in `new'
	from /usr/lib/ruby/gems/3.2.0/gems/balboa_worldwide_app-2.1.5/exe/bwa_mqtt_bridge:421:in `<top (required)>'
	from /usr/bin/bwa_mqtt_bridge:25:in `load'
	from /usr/bin/bwa_mqtt_bridge:25:in `<main>'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped**

Would you be able to help me troubleshoot where the issue might be?

**Comment by jshank** [comment]
This looks like you're losing wifi connection with the EW11. Run a continuous ping and see if that's the cause. The new "direct" method of connecting doesn't tolerate connectivity loss very well. Can you share your docker-compose.yaml file? Make sure you have `restart: unless-stopped`

**Comment by Ares4570** [comment]
I'm seeing a similar error, with  0.3% packet loss (tested over 5 minute span) which I'd consider normal with WiFi. Is there any way to have it automatically recover in these instances of connectivity loss?

Most recently, this happened overnight and the docker container didn't update anything until it (seemingly) crashed and restarted automatically after a few failed commands from Home Assistant.
